import {
  createWalletClient,
  createPublicClient,
  http,
  parseAbi,
} from "viem";
import { privateKeyToAccount } from "viem/accounts";
import { mainnet, sepolia } from "viem/chains";
import { pinReport } from "../utils/ipfs.js";
import type {
  AuditResult,
  ExploitTestResult,
  PublishResult,
} from "../utils/types.js";

const REGISTRY_ABI = parseAbi([
  "function publishAudit(address target, uint8 riskScore, string calldata verdict, string calldata reportCID, uint8 confirmedExploits) external",
]);

export async function publishAudit(
  address: string,
  contractName: string,
  audit: AuditResult,
  testResults: ExploitTestResult[],
  chain: string = "ethereum"
): Promise<PublishResult> {
  // Generate markdown report
  const markdown = generateMarkdownReport(
    address,
    contractName,
    audit,
    testResults
  );

  // Upload to IPFS
  const ipfsCid = await pinReport(markdown, address);

  // Write to on-chain registry
  const txHash = await writeToRegistry(address, audit, testResults, ipfsCid, chain);

  return { ipfsCid, txHash };
}

function generateMarkdownReport(
  address: string,
  contractName: string,
  audit: AuditResult,
  testResults: ExploitTestResult[]
): string {
  const confirmedCount = testResults.filter((t) => t.passed).length;
  const theoreticalCount = testResults.filter(
    (t) => t.compiled && !t.passed
  ).length;
  const timestamp = new Date().toISOString();

  let md = `# ContractLens Audit Report

## Summary
- **Contract:** \`${address}\`
- **Name:** ${contractName}
- **Verdict:** ${audit.verdict}
- **Risk Score:** ${audit.riskScore}/100
- **Confidence:** ${audit.confidence}%
- **Date:** ${timestamp}

${audit.summary}

---

## Exploits Found

`;

  if (audit.exploits.length === 0) {
    md += "No exploits were identified.\n\n";
  } else {
    for (const exploit of audit.exploits) {
      const testResult = testResults.find((t) => t.exploitId === exploit.id);
      const status = testResult
        ? testResult.passed
          ? "CONFIRMED"
          : testResult.compiled
            ? "THEORETICAL"
            : "UNTESTED"
        : "NOT TESTED";

      md += `### ${exploit.id} — ${exploit.severity} ${status === "CONFIRMED" ? "🔴" : status === "THEORETICAL" ? "🟡" : "⚪"}

- **Severity:** ${exploit.severity}
- **Status:** ${status}
- **Functions:** ${exploit.functions.join(", ")}
- **Description:** ${exploit.description}
- **Attack Scenario:** ${exploit.attackScenario}
- **Mitigation:** ${exploit.mitigation} (${exploit.mitigationLevel})

`;
    }
  }

  md += `---

## Statistics
- **Total Exploits:** ${audit.exploits.length}
- **Confirmed (via Foundry fork test):** ${confirmedCount}
- **Theoretical (test failed):** ${theoreticalCount}
- **Critical:** ${audit.exploits.filter((e) => e.severity === "CRITICAL").length}
- **High:** ${audit.exploits.filter((e) => e.severity === "HIGH").length}
- **Medium:** ${audit.exploits.filter((e) => e.severity === "MEDIUM").length}
- **Low:** ${audit.exploits.filter((e) => e.severity === "LOW").length}

---

## Disclaimer
This audit was generated by ContractLens, an AI-powered smart contract analysis tool.
It should not be considered a substitute for a professional manual audit.
AI-generated findings may contain false positives or miss certain vulnerabilities.
Always conduct thorough due diligence before interacting with any smart contract.

---

*Generated by ContractLens on ${timestamp}*
`;

  return md;
}

async function writeToRegistry(
  address: string,
  audit: AuditResult,
  testResults: ExploitTestResult[],
  ipfsCid: string,
  chain: string
): Promise<string> {
  const registryAddress = process.env.REGISTRY_ADDRESS;
  const privateKey = process.env.PRIVATE_KEY;
  const rpcUrl = process.env.RPC_URL;

  if (!registryAddress || !privateKey || !rpcUrl) {
    return "0x0 (skipped — missing REGISTRY_ADDRESS, PRIVATE_KEY, or RPC_URL)";
  }

  const account = privateKeyToAccount(
    (privateKey.startsWith("0x") ? privateKey : `0x${privateKey}`) as `0x${string}`
  );

  const viemChain = chain.toLowerCase() === "sepolia" ? sepolia : mainnet;

  const walletClient = createWalletClient({
    account,
    chain: viemChain,
    transport: http(rpcUrl),
  });

  const publicClient = createPublicClient({
    chain: viemChain,
    transport: http(rpcUrl),
  });

  const confirmedExploits = testResults.filter((t) => t.passed).length;
  const riskScore = Math.min(Math.max(audit.riskScore, 0), 255);

  const hash = await walletClient.writeContract({
    address: registryAddress as `0x${string}`,
    abi: REGISTRY_ABI,
    functionName: "publishAudit",
    args: [
      address as `0x${string}`,
      riskScore,
      audit.verdict,
      ipfsCid,
      confirmedExploits,
    ],
  });

  // Wait for confirmation
  await publicClient.waitForTransactionReceipt({ hash });

  return hash;
}
